language: node_js
node_js: 8
cache:
  directories:
    - .cargo-install
  cargo: true
  # Yarn cache blows up to be too big
  #yarn: true

before_install:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - CARGO_TARGET_DIR=.cargo-install cargo install cargo-web
  - CARGO_TARGET_DIR=.cargo-install cargo install --git https://github.com/alexcrichton/wasm-gc
  - CARGO_TARGET_DIR=.cargo-install cargo install --git https://github.com/alexcrichton/wasm-bindgen

script:
  - travis_wait yarn test
  - for example in simple advanced-stdweb advanced-wasm-bindgen; do (cd examples/$example; yarn; yarn build); done
